kind: pipeline
name: default

workspace:
  #base: /ci
  #path: serverless-cpp-example
  base: /ci/serverless-cpp-example
  path: "."

steps:
  - name: test
    image: paulreimer/aws-lambda-cpp:latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
    commands:
      - cd build
      - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/local
      - ninja-build test_example
      - ninja-build test

  - name: package
    image: paulreimer/aws-lambda-cpp:latest
    commands:
      - cd build
      - ninja-build aws-lambda-package-example

  - name: deploy
    image: giusedroid/drone-serverless
    settings:
      action: deploy
    environment:
      PLUGIN_AWS_SECRET_ACCESS_ID:
        from_secret: deploy_aws_secret_access_id
      PLUGIN_AWS_SECRET_KEY:
        from_secret: deploy_aws_secret_key

node:
  cloud.google.com/gke-os-distribution: ubuntu
