kind: pipeline
name: default

workspace:
  #base: /ci
  #path: serverless-cpp-example
  base: /ci/serverless-cpp-example
  path: "."

steps:
  - name: test
    image: paulreimer/aws-lambda-cpp:latest
    privileged: true
    commands:
      #- mkdir -p build
      #
      #- yum -y update
      #- yum -y install acl policycoreutils-python
      #- getfacl build
      #- semanage fcontext -l
      #
      - cd build
      - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/local
      - ninja-build test_example
      - ninja-build test

  - name: package
    image: paulreimer/aws-lambda-cpp:latest
    privileged: true
    commands:
      - cd build
      - ninja-build aws-lambda-package-example
