kind: pipeline
name: default

workspace:
  base: /ci/serverless-cpp-example
  path: "."

steps:
  - name: test
    image: gcr.io/p-rimes-net/aws-lambda-cpp:latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
    commands:
      - cd build
      - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/local
      - ninja-build test_example
      - ninja-build test

  - name: package
    image: gcr.io/p-rimes-net/aws-lambda-cpp:latest
    commands:
      - cd build
      - ninja-build aws-lambda-package-example

  - name: npm
    image: gcr.io/p-rimes-net/drone-serverless:1.36.1
    commands:
      - npm install
    environment:
      HOME: "/tmp"
    when:
     event: promote

  - name: deploy_dev
    image: gcr.io/p-rimes-net/drone-serverless:1.36.1
    settings:
      action: deploy
      aws_secret_access_id:
        from_secret: deploy_aws_secret_access_id
      aws_secret_key:
        from_secret: deploy_aws_secret_key
    environment:
      HOME: "/tmp"
    when:
     event: promote
     environment: dev

  - name: deploy_production
    image: gcr.io/p-rimes-net/drone-serverless:1.36.1
    settings:
      action: deploy
      aws_secret_access_id:
        from_secret: deploy_aws_secret_access_id
      aws_secret_key:
        from_secret: deploy_aws_secret_key
    environment:
      HOME: "/tmp"
    when:
     event: promote
     environment: production

node:
  beta.kubernetes.io/instance-type: g1-small
