kind: pipeline
name: default

workspace:
  #base: /ci
  #path: serverless-cpp-example
  base: /ci/serverless-cpp-example
  path: "."

steps:
  - name: test
    image: gcr.io/p-rimes-net/aws-lambda-cpp:latest
    privileged: true
    commands:
      - mkdir -p build
      - cd build
      - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/local -DCTEST_BINARY_OUTPUT_DIRECTORY=/tmp/
      - ninja-build test_example
      - ninja-build test

  - name: package
    image: gcr.io/p-rimes-net/aws-lambda-cpp:latest
    privileged: true
    commands:
      - mkdir -p build
      - cd build
      - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/local
      - ninja-build aws-lambda-package-example
