kind: pipeline
name: default

workspace:
  #base: /ci
  #path: serverless-cpp-example
  base: /ci/serverless-cpp-example
  path: "."

steps:
  - name: test
    image: gcr.io/p-rimes-net/aws-lambda-cpp:latest
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
    commands:
      - cd build
      - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/local
      - ninja-build test_example
      - ninja-build test

  - name: package
    image: gcr.io/p-rimes-net/aws-lambda-cpp:latest
    commands:
      - cd build
      - ninja-build aws-lambda-package-example

  - name: deploy
    image: paulreimer/drone-serverless
    settings:
      action: deploy
      aws_secret_access_id:
        from_secret: deploy_aws_secret_access_id
      aws_secret_key:
        from_secret: deploy_aws_secret_key
    volumes:
      - name: tmproot
        path: /root

volumes:
  - name: tmproot
    temp: {}

node:
  cloud.google.com/gke-os-distribution: ubuntu
